name: Lint
on:
  push:
    branches:
      - master
      - main
    tags:
    pull_request:

concurrency:
  group: ci-${{ github.ref }}-lint
  cancel-in-progress: true

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      # since golangci-lint-action@v3 we need to run setup-go@v2 first
    - uses: actions/setup-go@v2
      with:
        go-version: '1.17'
    - name: Checkout
      uses: actions/checkout@v2
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.45
        args: --timeout 5m
